---
name: build-modules-images

on:
    workflow_dispatch:

jobs:
    modules:
        environment: docker-hub
        runs-on: ubuntu-latest
        steps:
            # https://github.com/docker/login-action
            - id: login
              name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            # https://github.com/docker/setup-qemu-action
            - id: setup-qemu
              name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - id: setup-buildx
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - uses: actions/checkout@v3
            - id: build-perl-5-40-2-modules
              name: Build modules for 5.40.2
              run: |
                perl layers/modules-base/build-modules-base-images.pl 5.40.2

