---
name: build-modules-images

on:
    workflow_dispatch:

jobs:
    modules:
        environment: docker
        runs-on: ubuntu-latest
        steps:
            - id: login
              name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            # https://github.com/docker/setup-qemu-action
            - id: setup-qemu
              name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - id: setup-buildx
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
